package org.firstinspires.ftc.teamcode.utils.math;

import com.pedropathing.math.Matrix;
import com.pedropathing.math.Vector;

import org.firstinspires.ftc.teamcode.utils.math.calc.Vector2D;

public class Ellipse2D {
    public final Matrix characteristic;
    public final double theta;
    public final double[] eigenvalues;

    public Ellipse2D(Matrix characteristic) {
        if (characteristic.getColumns() != 2 || characteristic.getRows() != 2)
            throw new IllegalArgumentException("Ellipse2D must be generated by 2x2 matrix");
        this.characteristic = characteristic;
        double A = characteristic.get(0, 0);
        double B = characteristic.get(1, 0);
        double C = characteristic.get(1, 1);

        if (Math.abs(characteristic.get(0, 1) - B) < 1e-6)
            throw new IllegalArgumentException("Ellipse2D must be generated by symmetric matrix");

        double discriminant = Math.sqrt((A - C) * (A - C) / 4 + B * B);
        double vertex = (A + C) / 2;
        double eigen1 = vertex - discriminant;
        double eigen2 = vertex + discriminant;

        if (eigen1 < 0)
            throw new IllegalArgumentException("Ellipse2D must be generated by positive-definite matrix");

        eigenvalues = new double[] {eigen1, eigen2};
        theta = 0.5 * Math.atan2(2 * B, A - C);
    }

    public Ellipse2D(double theta, double[] eigenvalues) {
        this.eigenvalues = eigenvalues;
        this.theta = theta;
        Matrix rotation = MathUtil.rotMatrix(theta);
        characteristic = rotation.times(Matrix.diag(eigenvalues).times(rotation.transposed()));
    }

    public Ellipse2D(double theta, double majorAxis, double minorAxis) {
        this.eigenvalues = new double[] {1 / majorAxis / majorAxis, 1 / minorAxis / minorAxis};
        this.theta = theta;
        Matrix rotation = MathUtil.rotMatrix(theta);
        characteristic = rotation.times(Matrix.diag(eigenvalues).times(rotation.transposed()));
    }

    public Ellipse2D(double majorAxis, double minorAxis) {
        eigenvalues = new double[] {1 / majorAxis / majorAxis, 1 / minorAxis / minorAxis};
        characteristic = Matrix.diag(eigenvalues);
        theta = 0;
    }

    /**
     Constructs a circle
     */
    public Ellipse2D(double radius) {
        this(radius, radius);
    }

    public double getMajorAxis() {
        return 1 / Math.sqrt(eigenvalues[0]);
    }

    public double getMinorAxis() {
        return 1 / Math.sqrt(eigenvalues[1]);
    }


    public boolean interiorPoint(Vector2D point) {
        return point.quadraticForm(characteristic) < 1;
    }

    public boolean onBoundary(Vector2D point) {
        return Math.abs(point.quadraticForm(characteristic) - 1) < 1e-6;
    }

    public boolean outside(Vector2D point) {
        return point.quadraticForm(characteristic) > 1 + 1e-6;
    }

    public Ellipse2D rotate(double theta) {
        return new Ellipse2D(this.theta + theta, eigenvalues);
    }

    public Vector2D interpolate(Vector2D vector) {
        Vector2D unit = vector.normalize();
        return unit.times(1 / Math.sqrt(unit.quadraticForm(characteristic)));
    }

    public Vector interpolate(double phi) { // \phi = 0 is at major axis, \phi = Math.PI/2 is at minor axis
        Vector unit = new Vector(1, theta + phi);
        return unit.times(1 / Math.sqrt(unit.dot(unit.transform(characteristic))));
    }

    public double radius(double phi) {
        double xTerm = Math.cos(phi) / getMajorAxis();
        double yTerm = Math.sin(phi) / getMinorAxis();
        return 1 / Math.hypot(xTerm, yTerm);
    }

    public static Ellipse2D fromAxes(double forwardAxis, double lateralAxis) {
        if (forwardAxis >= lateralAxis) return new Ellipse2D(forwardAxis, lateralAxis);
        else return new Ellipse2D(Math.PI / 2, lateralAxis, forwardAxis);
    }
}
